framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: duoimport/website

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # APCu (recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        app: cache.adapter.filesystem
        system: cache.adapter.filesystem

        # Namespaced pools use the above "app" backend by default
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

when@prod:
    framework:
        cache:
            app: cache.adapter.filesystem
            system: cache.adapter.filesystem
