web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler:
        enabled: true
        collect: true
        only_exceptions: false
        only_main_requests: false 