name: Symfony CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, gd, xml, ctype, iconv
        coverage: none
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Check PHP syntax errors
      run: find ./src -type f -name "*.php" -exec php -l {} \;
      
    - name: Check Symfony requirements
      run: php bin/console about
      
    - name: Clear cache
      run: php bin/console cache:clear
      
    # Uncomment when you have tests
    # - name: Run tests
    #   run: php bin/phpunit
    
    - name: Create .env file
      run: |
        echo "APP_ENV=${{ secrets.APP_ENV }}" > .env
        echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
        echo "MAILER_DSN=${{ secrets.MAILER_DSN }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      
    - name: Déploiement sur le serveur FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Répertoire de build
        server-dir: /  # Répertoire distant
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env.local
          .env.test
          .env